[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "requests>=2.32.3",
    "selenium>=4.30.0",
    "tqdm>=4.67.1",
    "webdriver-manager>=4.0.2",
]
