name: Auto Update JSON and Trigger Deploy

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Sync dependencies and run main.py
        run: |
          uv sync
          source .venv/bin/activate
          python main.py

      - name: Commit and push updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/pokemon_cards.json
          git commit -m "(chore): auto-update JSON" || echo "Nothing to commit"
          git push

  trigger-deploy:
    needs: update-json
    uses: ./.github/workflows/deploy.yml
